### ISSUE TITLE
[Lobe theme] Double button display

### ISSUE THREAD

**Issue by alexbofa** [LEv145/--sd-webui-ar-plus#11]
Hello, I have [Lobe Theme](https://github.com/canisminor1990/sd-webui-lobe-theme).
There is a problem with displaying buttons.
![Screen-1100](https://github.com/LEv145/--sd-webui-ar-plus/assets/58225118/70193e51-87cd-4758-95d7-9fd04ac5ea13)

**Comment by LEv145** [comment]
The problem is that the developer added an external style for `modules.ui_components.ToolButton`, which is why the `visible` property does not work with `ToolButton`
```py
arc_hide_calculator = ToolButton(
    value=CALCULATOR_SYMBOL,
    visible=False,
    variant="primary",
    elem_id="arsp__arc_hide_calculator_button",
)
```
https://github.com/canisminor1990/sd-webui-lobe-theme/blob/d4c4a48e8025d32b202716d4ab8d806580752256/src/styles/components/button.ts#L10

But because of this, the pressed button will not differ from not pressed
https://github.com/canisminor1990/sd-webui-lobe-theme/blob/d4c4a48e8025d32b202716d4ab8d806580752256/src/styles/components/button.ts#L25

**Comment by LEv145** [comment]
Quick fix

`style.css`:
```css
...
/* Fix for Lobe theme */
/* https://github.com/canisminor1990/sd-webui-lobe-theme/blob/d4c4a48e8025d32b202716d4ab8d806580752256/src/styles/components/button.ts */
.hide.svelte-1ipelgc {
	display: none !important;
}

.primary.svelte-1ipelgc {
	background: var(--button-primary-background-fill) !important;
}

.secondary.svelte-1ipelgc {
	background: var(--button-secondary-background-fill) !important;
}
```
